apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: furniture-customize
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bhavikgadher/furniture-customizer-backend:latest # Update this image tag
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: "3000"
          - name: DB_HOST
            value: "postgresql-service"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: furniture-customize-config-map
                key: POSTGRES_DB
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: furniture-customize-secrets
                key: POSTGRES_PASSWORD
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 45
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: furniture-customize
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
