apiVersion: v1
kind: ConfigMap
metadata:
  name: furniture-customize-config-map
  namespace: furniture-customize
data:
  POSTGRES_DB: mainbackend
  DB_NAME: mainbackend
  POSTGRES_USER: postgres
  DB_USER: postgres
  DB_HOST: postgresql-service
  DB_PORT: "5432"
