kind: Secret
apiVersion: v1
metadata:
  name: furniture-customize-secrets
  namespace: furniture-customize
type: Opaque

data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  ##base64 encode for "postgres"
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: bXktc3VwZXItc2VjcmV0LWp3dC1rZXk=  ##base64 encode for "my-super-secret-jwt-key"
