apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui-deployment
  namespace: furniture-customize
  labels:
    app: user-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
    spec:
      containers:
      - name: user-ui
        image: bhavikgadher/furniture-customizer-app:0c0525a5ff7af20c6a53a70b41f597ae5531e74a
        ports:
        - containerPort: 8080
        env:
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: "8080"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user-ui-service
  namespace: furniture-customize
spec:
  selector:
    app: user-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
